### ISSUE TITLE
License

### ISSUE THREAD

**Issue by afeder** [addwiki/mediawiki-api-base#4]
Please add a LICENSE file or similar indicating licensing terms.

**Comment by addshore** [comment]
Hi!

I have added https://github.com/addwiki/mediawiki-api-base/commit/327652df6f1bde0a1a7b90c522f4f3d118602f76

The licence was already visible in the composer.json file here https://github.com/addwiki/mediawiki-api-base/blob/master/composer.json#L6

But yes! This should be more visible! Thanks for the note!
